BLOCK_SIZE = 20
SCREEN_WIDTH = 400
SCREEN_HEIGHT = 400
GRID_WIDTH = SCREEN_WIDTH // BLOCK_SIZE
GRID_HEIGHT = SCREEN_HEIGHT // BLOCK_SIZE

__all__ = [
    "BLOCK_SIZE",
    "SCREEN_WIDTH",
    "SCREEN_HEIGHT",
    "GRID_WIDTH",
    "GRID_HEIGHT",
]